baseURL: 'http://tylerperkins.xyz'
languageCode: 'en-us'
title: "Tyler Perkins"

outputs:
  page:
    - HTML
    - markdown

outputFormats:
  markdown:
    mediaType: "text/markdown"
    isPlainText: true
    isHTML: false
    permalinkable: false
    name: "markdown"
    path: ""
    baseName: "index"
    rel: "alternate"
